##################################
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#
# Makefile for XWT library
#

TARGET=libxwt.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
XWT_INSTALL=../lib

CSOURCES=xwt_api.c

include ../Rules.make
