#
# $Id: Makefile 9611 2012-07-30 09:32:54Z lculik $
#

ROOT = ../../

C_SOURCES=\
	expropt1.c \
	expropt2.c \
	hbfsapi.c \
	hbfopen.c \
	hbgete.c \
	hbwince.c \
	hbhash.c \
	hbstr.c \
	hbprintf.c \
	hbdate.c \
	hbtrace.c \
	hbver.c \
	hbarch.c \
	reserved.c \
	hbmem.c \

PRG_SOURCES=\

LIBNAME=common

include $(TOP)$(ROOT)config/lib.cf
