#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES=\

PRG_SOURCES=\
    thtm.prg \
    tcgi.prg \
    tedit.prg \
    tframe.prg \
    tfile.prg \
    hjwindow.prg \
    hterrsys.prg \
    htmutil.prg \
    htjlist.prg \

LIBNAME=cgi

DIRS=include

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
