##################################
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#
# Makefile for XWT GTK interface
#

TARGET=libxwt_gtk.a
CFLAGS+=-I. -I../include `pkg-config --cflags gtk+-2.0` -fms-extensions

SOURCE_TYPE=c
XWT_INSTALL=../lib

include ../Rules.make
