##################################
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#
# Makefile for GD library
#

TARGET=libgdlib.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
TGD_INSTALL=../lib

CSOURCES=gdwrp.c

include ../Rules.make
