##################################
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#
# Toplevel TGD makefile

all:
	make -C source
	#make -C test

clean:
	make -C source clean
	#make -C test clean
	rm -f lib/*.a


install:
	make -C source install
