#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

PRG_SOURCES=\
	dbgmenu.prg  \
	dbghelp.prg  \
	dbgtmenu.prg \
	dbgtmitm.prg \
	dbgtwin.prg  \
	debugger.prg \
	dbgaltd.prg  \
	dbgtarr.prg  \
	dbgthsh.prg  \
	dbgtobj.prg  \
	tbrwtext.prg \
	dbgwa.prg    \
  dbgbrwsr.prg

LIBNAME=debug

include $(TOP)$(ROOT)config/lib.cf
