#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES= \
	hbppcore.c \
	hbppcomp.c \
	hbppcalc.c \
	hbpptbl.c  \
	pragma.c   \

C_MAIN=hbpp.c

LIBS=\
	common \

include $(TOP)$(ROOT)config/bin.cf
