/*
 * $Id: hpdf_version.h 9279 2011-02-14 18:06:32Z druzus $
 */
/* automatically generated by configure */
/* edit configure.in to change version number */
#define HPDF_MAJOR_VERSION 2
#define HPDF_MINOR_VERSION 2
#define HPDF_BUGFIX_VERSION 1
#define HPDF_EXTRA_VERSION ""
#define HPDF_VERSION_TEXT "2.2.1"
#define HPDF_VERSION_ID 20201
