#
# $Id: Makefile 9403 2011-11-08 17:27:36Z lculik $
#

ROOT = ../../

C_SOURCES= \

C_MAIN=hbfilere.c

LIBS=\
	debug \
	vm \
	rtl \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	lang \
	common \
	ct \
	rtl \
	vm \

include $(TOP)$(ROOT)config/bin.cf
