#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../

DIRS=\
	hbpp \
	hbrun \
	hbdoc \
	hbtest \
	hbmake \
	hbdict \
	hbfilere \
	xbscript \
	$(HB_UTILS) \
#	hbextern \

include $(ROOT)config/dir.cf
