##################################
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#
# Makefile for FreeImage library
#

TARGET=libfi.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
TGD_INSTALL=../lib

CSOURCES=fi_wrp.c

include ../Rules.make
