#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ifeq ($(HB_MAIN),)
 HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
	hbextern.prg \

PRG_MAIN=hbextern.prg

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	ct \
	rtl \
	vm \
	macro \
	pp \
	common \

include $(TOP)$(ROOT)config/bin.cf
