#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ifeq ($(HB_MAIN),)
 HB_MAIN = std
endif

ROOT = ../../../

CONTRIBS=\
        postgres \

PRG_SOURCES=\
        test.prg \

PRG_MAIN=\
	test.prg

LIBS=\
        debug \
        vm \
        rtl \
        lang \
        rdd \
        rtl \
        vm \
        macro \
        common \
	pq \

include $(TOP)$(ROOT)config/bin.cf

